export const ErrorCodes = {
  VALIDATION_ERROR: "VALIDATION_ERROR",

  ACCOUNT_NOT_FOUND: "ACCOUNT_NOT_FOUND",

  CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",

  TRANSACTION_NOT_FOUND: "TRANSACTION_NOT_FOUND",

  DUPLICATE_CATEGORY: "DUPLICATE_CATEGORY",

  DATABASE_ERROR: "DATABASE_ERROR",

  UNKNOWN_ERROR: "UNKNOWN_ERROR",
} as const;